<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\Authentication\" />
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Data\" />
    <Folder Include="Members\" />
    <Folder Include="Admins\" />
    <Folder Include="MyAccount\" />
    <Folder Include="MyTrips\GetMyTrips\" />
    <Folder Include="MyTrips\GetMyTripById\" />
    <Folder Include="Trips\DeleteTrip\" />
    <Folder Include="Trips\GetTrips\" />
    <Folder Include="Trips\GetTripById\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\TrackMe.Domain\Domain.csproj" />
  </ItemGroup>

</Project>
