<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Admins\" />
    <Folder Include="Members\GetMemberById\" />
    <Folder Include="MyAccount\" />
    <Folder Include="MyTrips\GetMyTrips\" />
    <Folder Include="MyTrips\GetMyTripById\" />
    <Folder Include="Trips\DeleteTrip\" />
    <Folder Include="Trips\GetTrips\" />
    <Folder Include="Trips\GetTripById\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\TrackMe.Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttibute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>TrackMe.Application.UnitTests</_Parameter1>
    </AssemblyAttibute>
   </ItemGroup>
  
</Project>
